### ISSUE TITLE
[BUG] Read-only state "rct.0.info.connection" has been written without ack-flag with value "false"

### ISSUE THREAD

**Issue by mcm1957** [aruttkamp/ioBroker.rct#107]
**Describe the bug**  
Read-only state "rct.0.info.connection" has been written without ack-flag with value "false"

**To Reproduce**  
Configure an instance and use an ip-address which is unused 

**Expected behavior**  
info.connectio  shoudl always be set correctly

**Screenshots & Logfiles**  
If applicable, add screenshots and logfiles to help explain your problem.

**Versions:**  
 - Adapter version: 1.2.4
 - JS-Controller version: 5.0.19
 - Node version: 18.20.1
 - Operating system: Raspbian

**Additional context**

**Comment by NCIceWolf** [comment]
Auch dieses Thema sollte mit 1.2.5 erledigt sein.
Bitte um kurze Bestätigung 😃

**Comment by aruttkamp** [comment]
Taucht nicht mehr im Log auf !
