### ISSUE TITLE
rct has an invalid jsonConfig

### ISSUE THREAD

**Issue by jomahol** [aruttkamp/ioBroker.rct#135]
Moinsen...
erstmal, der Adapter läuft hier hervorragend und fehlerfrei vielen Dank dafür... einzig jedesmal wenn ich die rct-instanz Konfiguration aufrufe (Klick auf Schraubenschlüssel) erscheint im Protokoll folgender Fehler:

admin.0 (321180) rct has an invalid jsonConfig: [{"instancePath":"","schemaPath":"#/then/required","keyword":"required","params":{"missingProperty":"type"},"message":"must have required property 'type'"}]

Kein Plan was mir das sagen soll! 

Die Fehlermeldung bleibt auch nach einer Adapter Neuinstallation !

RCT-Adapter 1.29
CPU: 22,07 %
RAM: 69 %
Betriebszeit: 0h
Verfügbar: 5.0.19
Installiert: 5.0.19
Ereignisse: ⇥25 / ↦13
Plattform: linux
Betriebssystem: linux
Architektur: x64
CPUs: 4
Geschwindigkeit: 2595 MHz
Modell: Intel(R) Celeron(R) J4125 CPU @ 2.00GHz
RAM: 5.6 GB
Node.js: v18.20.3
NPM: 10.7.0
Datenträgergröße: 468.4 GB
Freier Festplattenspeicher: 453.6 GB
Aktive Instanzen: 16
Pfad: /opt/iobroker/

**Comment by mcm1957** [comment]
@aruttkamp 
This is a issue with yout jsonConfig.json. There is no type specified at top level. 
Please correct
