### ISSUE TITLE
inverter_state

### ISSUE THREAD

**Issue by mosandlt** [aruttkamp/ioBroker.rct#186]
leider kann ich den inverter_state wie auf der Hauptseite beschrieben nirgends finden. 

evtl heist der wert anders oder ihn gibt es nicht mehr?

**Comment by aruttkamp** [comment]
Das ist ein Fehler in der Doku - Bisher unbemerkt. 
korrekt müsste es der Parameter "prim_sm.state" sein.

**Comment by Madaraxa** [comment]
Hey,
ich will dich @aruttkamp nicht "nerven", aber das hier ist nicht fixed :) ich habe gerade viele verschiedene states manuell ausprobiert um den "inverter_state" zu finden, der beschrieben wird. Bis ich auf die Idee gekommen bin in den closed issues zu suchen.
Außerdem finde ich den selber "wichtig", da man hiermit leicht mit Hilfe von einem Skript auf einen Fehler hingewiesen werden kann.
Ich habe seit einigen Wochen einmal wöchentlich "BAT_OVERVOLTAGE" Meldungen. Dann ist die Batterie Spannung >500Volt und der WR startet neu - ich versuche beim nächsten Mal herauszufinden, ob dann hier eine andere Nummer steht außer die dokumentierten 0-13. Evtl. könnte man den zu den Standard States hinzufügen (zumal er explizit in der Doku beschrieben wird).

**Comment by NCIceWolf** [comment]
Hab das eben nochmal getestet und das bei den abzufragenden Werten hinzugefügt:
"prim_sm.state"

Im Log sehe ich dann folgendes:
RCT: received: prim_sm.state: 13

Passt auch einwandfrei, da gerade noch eingespeist wird (grid feeding). Aus meiner Sicht funktioniert das mit der aktuellen Version also einwandfrei.

Könntest du mal schauen dass der Wert sauber eingetragen ist und im Zweifel den Log auf Debug stellen und das erweiterte Logging aktivieren?
Vielleicht sehen wir dann woran es hängt.

**Comment by Madaraxa** [comment]
Sorry. Dann hab ich mich schlecht ausgedrückt. In der Doku ist nicht gefixed, dass der state nicht 'Inverter_state' heißt, sondern prim_sm.state
Es funktioniert, aber wenn man den Status des Wechselrichters als Objekt haben möchte, findet man den nicht, da in der Doku steht:

The object "inverter_state" indicates the status of the inverter

0 -> 'Standby'
1 -> 'Initialization'
2 -> 'Standby'.....

Entschuldige das Missverständnis.

**Comment by NCIceWolf** [comment]
Ist kein Problem, hab ich verstanden.
@aruttkamp: Da es ja nur die Doku betrifft, hab ich das direkt angepasst. Also kein To-Do für dich
