### ISSUE TITLE
Hausverbrauch nicht auszuwerten ..

### ISSUE THREAD

**Issue by jonaslinhose** [aruttkamp/ioBroker.rct#23]
Hallo,

vielleicht stehe ich auf dem Schlauch, aber ich versuche den Hausverbrauch auszulesen. Leider finde ich keinen passenden Wert, der die entsprechende Werte zurück gibt.
Ich habe schon die main.js bzw. rct_core.js durchgesehen und einige andere nützliche Werte gefunden, aber leider nichts passendes für den Hausverbrauch. Hat hier jmd. einen Tip für mich?

Viele Dank

Jonas

**Comment by NCIceWolf** [comment]
Moin!

Hab ich per Zufall gerade gestern auf mein Dashboard gepackt und nehme dafür diesen hier:
rct.0.g_sync.p_ac_load_sum_lp

Bitte um Rückmeldung wenn das passt.

VG
Matthias

**Comment by aruttkamp** [comment]
Moin ! 

Ich kann aktuell nicht helfen, da meine Anlage immer noch nicht vollständig ist und ich den Hausverbrauch nicht von RCT bekomme. Ich hoffe das hat im August ein Ende ;-) 
Rein von der Logik her müsste der Wert von NCIceWolf korrekt sein , also rct.0.g_sync.p_ac_load_sum_lp
Schau mal was der dir ausgibt. 
Ich ermittel mir das aktuell aus dem Wert der Erzeugung - Einspeisung ;-) 
Nicht so genau , aber besser wie nix.

**Comment by jonaslinhose** [comment]
Hallo,

also bei mir zeigt p_ac_load_sum_lp aktuell 4584W an, die RCT - Power App aktuell zwischen 150W und 250W (wir sind nicht zuhause), dass passt also zumindest bei mir nicht. Es könnte ungefähr der Tagesverbrauch sein (18 * 250W).

Ich habe den aktuellen Hausverbrauch auch nur rechnerisch ermitteln können:
    AC Leistung meiner beiden Strings (rct.0.g_sync.p_ac_sum_lp) -- Die Ladung in den RCT-Akku ist da meiner Meinung nach nicht mit dabei --
+ AltePV-Anlage als externer Generator (rct.0.io_board.s0_external_power) 
+ Netzeinspeisung (rct.0.g_sync.p_ac_grid_sum_lp) 
+ Wallbox-Ladeleistung 

Falls jmd noch eine bessere Idee hat gerne. Ich suche auch noch eine Möglichkeit den Hausverbrauch (täglich, wöchentlich, mtl. jährlich) zu ermitteln, dass Finanzamt wäre begeistert.

**Comment by NCIceWolf** [comment]
![Screenshot_20230709-111308](https://github.com/aruttkamp/ioBroker.rct/assets/127289023/330484c1-05cc-43f2-9df2-5ce5c55b9091)

Ich würde da noch einmal drauf schauen, bei mir passt das. Zuerst der "Standby-Verbrauch", dann würden zwei Herdplatten angeschaltet.

Dabei zu beachten: der Wert wird ja je nach Einstellung aus dem Wechselrichter ausgelesen (bei mir alle 10 Sekunden).
Das RCT Power Portal ist wesentlich langsamer (da in die Cloud synchronisiert), die RCT Power App wiederum ist schneller, da lokal.

Könnte aber noch ein Unterschied bei der Konfiguration  sein, habe den RCT WR 10 und eine Batterie. Vielleicht unterscheiden sich die Werte wenn keine Batterie vorhanden ist?

**Comment by jonaslinhose** [comment]
Hallo,

es ist seltsam, jetzt scheinen sich auch bei mir die Werte entsprechend zu aktualisieren und passen auch mit leichter Verzögerung zu der RCP PowerApp.  Es ist also wirklich der p_ac_load_sum_lp , was mir auch logisch erscheint. Danke für die Hinweise / Hilfe.

**Comment by NCIceWolf** [comment]
Na klar, sehr gerne!
Das Thema der täglichen/wöchentlichen Werte würde ich Mal hiermit testen, aber ohne Gewähr:

energy.e_load_day_sum

Sollte es auch für week und month geben.

**Comment by Corneys** [comment]
Hallo, 

ich habe auch eine Frage zu dem Hausverbrauch.
Für mich sieht es so aus, als sei rct.0.g_sync.p_ac_load_sum_lp ein komplett anderer Wert als der tatsächliche aktuelle Hausverbrauch. 

Wenn ich mir in der RCT Power App den Verbrauch anschaue, welcher in der Übersicht als das Haus angezeigt wird, stehen hier zur Zeit ca. 200W (für mich ein realistischer Wert, welcher sich auch z.B. beim Kochen nach oben bewegt)
Diese 200 W bekomme ich aber leider nirgends ausgelesen

Tippe ich in der App auf das Haus wird ganz oben der Wert "Haushaltslast - externe Erzeuger [W]" angezeigt, dies ist der Wert, welchen ich über rct.0.g_sync.p_ac_load_sum_lp ausgegeben bekomme.
Dieser Wert liegt aber bei -900, was ich mir nicht so richtig erklären kann.

Vielleicht hat da jemand von euch ja eine Idee.

Vielen Dank
Felix

**Comment by camast** [comment]
In meiner Anlage (PS6) ohne "externe Erzeuger" stimmen alle 3 Werte (rct.0.g_sync.p_ac_load_sum_lp, App, "Hauslast - Externe Erzeuger") in Betrag und Vorzeichen überein. Ich habe zu keinem Zeitpunkt unplausible Werte festgestellt.
Hast Du externe Erzeuger konfiguriert bzw. angeschlossen?

**Comment by Corneys** [comment]
In der Anlage sind zwei Wechselrichter als Master und Slave integriert. 
Der Slave wird in der Übersicht als "G" angezeigt. 

Auf dem Hinweis mit der externen Erzeugung habe ich noch mal etwas herumgerechnet.
Wenn ich den Wert welcher unter G angezeigt wird (rct.0.io_board.s0_external_power) von dem Wert welcher mir als "Haushaltslast - externe Erzeuger [W]" (rct.0.g_sync.p_ac_load_sum_lp) abziehe ergibt das den Wert welcher unter dem Haus als tatsächlicher Verbrauch dargestellt wird. 

So könnte ich mir auf jeden Fall mit einem Scrip behelfen, falls es keinen direkten Datenpunkt für mich gibt.

![Screenshot_20230719_160101_RCT Power App (002)](https://github.com/aruttkamp/ioBroker.rct/assets/25282259/ca6292a1-472d-4c68-bd18-f8fb7ba5ccd0)
