### ISSUE TITLE
V1.1.6 Problem

### ISSUE THREAD

**Issue by wiese-computer-brb** [aruttkamp/ioBroker.rct#32]
Bei mir wird die Instance als Fehler Angezeigt, die Werte werden aber in die Objekte geschrieben. ?

![grabilla Uh3312](https://github.com/aruttkamp/ioBroker.rct/assets/143525522/cad21249-d5c2-40db-a228-7295aa458f2c)

**Comment by wiese-computer-brb** [comment]
![grabilla Uh3312](https://github.com/aruttkamp/ioBroker.rct/assets/143525522/4197ae7d-6093-4f2a-8e38-7e462db16bf7)

**Comment by aruttkamp** [comment]
Das ist aktuell korrekt. Siehe Issue #30
