### ISSUE TITLE
Consider fixing issues reported by adapter checker

### ISSUE THREAD

**Issue by mcm1957** [aruttkamp/ioBroker.rct#35]
👀 [W513] "gulpfile.js" found in repo! Think about migrating to @iobroker/adapter-dev package

Da du bereits adapter-dev benutzt (lt. package.json) und keine gulp Befehle zu sehen sind, check mal ob gulpfile.js nicht löschbar wäre und gulp npm deinstalliert werden könnte.

Ev. Fragen bitte auch Telgramm - bin auch kein Spezialist dazu und will dich nirgend reinhetzen!

**Comment by aruttkamp** [comment]
erledigt und gelöscht ;-)
