### ISSUE TITLE
Consider using dependabot

### ISSUE THREAD

**Issue by mcm1957** [aruttkamp/ioBroker.rct#37]
It looks like you did not yet setup dependabot support; at least .github/dependaboit.yml is missing.

Please consider setting up dependabot support (and to ease life the workflow auto-merge.yml). Dependabot will ensure that your adapter uses the most recent versions of external packages and avoids problem due to outdted base libraries. Dependabit provides PRs at you repository to update the dependencies. Depending on you setting, especially on auto-merge.yml configuration no or only minor revisions will be outmatically merged into you main branch. All major revisions must (and should) be reviewed by you.

Hint: at least @iobroker/adapter-core is not up to date (actual release is 3.x.x)

**Comment by aruttkamp** [comment]
dependabot.yml and auto-merge.yml created.
