### ISSUE TITLE
Objektbaum "energy" wird nicht aktualisiert bzw. nicht angelegt

### ISSUE THREAD

**Issue by petermeter2000** [aruttkamp/ioBroker.rct#56]
Sämtliche Werte des Objektbaums "energy" werden bei mir seit einiger Zeit nicht mehr aktualisiert. Alle anderen Werte schon.
Habe den Adapter gestoppt, Ordnerbaum RCT/0 gelöscht und den Adapter neu gestartet. Alle Unterordner werden neu erzeugt - bis auf "energy".
Die Werte werden in der RCT Power App richtig angezeigt.
Hat noch jemand das Problem?

 - Adapter version: 1.22
 - RCT-Control version: 2.3.5661
 - RCT BMS version: 5599
 - RCT Power Storage DC 8.0

Danke für Eure Hilfe!

**Comment by aruttkamp** [comment]
Bitte poste deine Parameter .. 
Also den Inhalt des Feldes rct_elements aus der Konfiguration.

**Comment by petermeter2000** [comment]
![grafik](https://github.com/aruttkamp/ioBroker.rct/assets/149077728/16c28c44-058f-41b8-9785-117eea7aae1c)

**Comment by petermeter2000** [comment]
Irgendeine Idee? Bin ich der Einzige mit dem Problem?
Kann ich noch irgendwelche nützlichen Infos schicken?
rct_elements war und ist leer.
Danke für Eure Hilfe!

**Comment by NCIceWolf** [comment]
Hatte ich so auch noch nie. Gib doch die Parameter bei dir mal explizit in den rct_elements an und schau ob sie dann kommen.

**Comment by petermeter2000** [comment]
Wie sieht denn die Syntax aus?
Da mir der gesamte Baum fehlt, weiß ich auch nicht mehr, wie die einzelnen Werte dort heißen.

Am 29. Oktober 2023 10:12:37 MEZ schrieb NCIceWolf ***@***.***>:

**Comment by NCIceWolf** [comment]
Ich zitiere aus der Readme:

Default is "battery.bat_status,battery.soc,battery.soc_target,battery.soc_target_high,battery.soc_target_low,dc_conv.dc_conv_struct[0].p_dc_lp,dc_conv.dc_conv_struct[1].p_dc_lp,fault[0].flt,fault[1].flt,fault[2].flt,fault[3].flt,g_sync.p_ac_grid_sum_lp,g_sync.p_ac_load_sum_lp,g_sync.p_ac_sum_lp,g_sync.p_acc_lp,g_sync.u_sg_avg[0],g_sync.u_sg_avg[1],io_board.s0_external_power,power_mng.is_heiphoss,power_mng.state,power_mng.use_grid_power_enable,power_mng.u_acc_mix_lp"

**Comment by petermeter2000** [comment]
Vielen Dank, ich werde es am Donnerstag ausprobieren!

Am 29. Oktober 2023 10:58:34 MEZ schrieb NCIceWolf ***@***.***>:

**Comment by aruttkamp** [comment]
> Default is "battery.bat_status,battery.soc,battery.soc_target,battery.soc_target_high,battery.soc_target_low,dc_conv.dc_conv_struct[0].p_dc_lp,dc_conv.dc_conv_struct[1].p_dc_lp,fault[0].flt,fault[1].flt,fault[2].flt,fault[3].flt,g_sync.p_ac_grid_sum_lp,g_sync.p_ac_load_sum_lp,g_sync.p_ac_sum_lp,g_sync.p_acc_lp,g_sync.u_sg_avg[0],g_sync.u_sg_avg[1],io_board.s0_external_power,power_mng.is_heiphoss,power_mng.state,power_mng.use_grid_power_enable,power_mng.u_acc_mix_lp"

Und dieser Default wird genutzt , wenn KEIN Eintrag in rct_elements vorgenommen wird. 
Da in diesem default aber nicht ein parameter aus dem Ast "energy" angesprochen wird wird da auch nix aktualisiert. 

Also... rct_elements mit den Parametern füllen die ausgelesen werden sollen - dann klappt das auch. 

Und bevor die Frage kommt... 
Zitat aus Readme:
Other elements can be found in the code (file "rct/rc_core2.js"). But this is not self descriptive at all (even not really tested).

**Comment by NCIceWolf** [comment]
Kommt davon wenn man das nur eben am Handy rum kopiert...
Danke für das wache Auge!!

**Comment by aruttkamp** [comment]
@petermeter2000 - soweit alles geklärt ?

**Comment by petermeter2000** [comment]
Ich konnte es noch nicht testen, da ich erst heute Abend aus dem Urlaub zurück bin :-)
Theoretisch ist mir alles klar, unklar ist mir nur, warum beim erstmaligen installieren des Adapters alle Werte da waren. Und jetzt eben nicht mehr. Ich versuche es heute Abend mal mit der expliziten Eingabe einzelner Werte.
Ich habe auch schon überlegt, ob das daran liegt, dass mein Wechselrichter ausgetauscht werden musste...?
Ich halte Euch auf dem Laufenden. Vielen Dank auf alle Fälle schon mal für Euren Einsatz!!!

Am 31. Oktober 2023 22:56:43 MEZ schrieb Andreas Ruttkamp ***@***.***>:

**Comment by petermeter2000** [comment]
Hallo,
juhu, es hat geklappt. Habe die Default -Werte reinkopiert und noch die "Energy"-Werte aus der rct_core2.js dazu. Wunderbar!
Warum die ursprünglich mal drin waren und jetzt nicht mehr - keine Ahnung...
Nochmals vielen Dank für die Hilfe!!!

Am 31. Oktober 2023 22:56:43 MEZ schrieb Andreas Ruttkamp ***@***.***>:

**Comment by aruttkamp** [comment]
> Hallo, juhu, es hat geklappt. Habe die Default -Werte reinkopiert und noch die "Energy"-Werte aus der rct_core2.js dazu. Wunderbar! Warum die ursprünglich mal drin waren und jetzt nicht mehr - keine Ahnung... Nochmals vielen Dank für die Hilfe!!! Am 31. Oktober 2023 22:56:43 MEZ schrieb Andreas Ruttkamp ***@***.***>:
> […](#)
> @petermeter2000 - soweit alles geklärt ? -- Reply to this email directly or view it on GitHub: [#56 (comment)](https://github.com/aruttkamp/ioBroker.rct/issues/56#issuecomment-1788092652) You are receiving this because you were mentioned. Message ID: ***@***.***>

Sehr gut ! 
Dann schliesse ich hier ab ;-)
