### ISSUE TITLE
Warnung im Protokoll

### ISSUE THREAD

**Issue by jomahol** [aruttkamp/ioBroker.rct#89]
an sich nix dolles, hab' hier nur mehrmals am Tag das im Protokoll stehen:

**| warn | Read-only state "rct.0.info.connection" has been written without ack-flag with value "false"**

kann ich da was ändern, kannst du da was ändern oder soll das so?

**Comment by mcm1957** [comment]
Da versuchts du (oder ein Script von dir) offenbar auf diesen State zu schreiben. Der State sollte ausschließlich vom Adapter Code beschrieben werden.

**Comment by jomahol** [comment]
Aha, hab' vermutlich zumindest den Auslöser gefunden. Da der Adapter in älteren Versionen gerne mal abgestürzt ist und dadurch ein größeres Loch in den Aufzeichnungen hinterlassen hat,  lasse ich die Instanz einmal pro Stunde neu starten. 
Habe  das jetzt mal manuell versucht... als Ergebniss: Jeder Restart des Adapters löst hier diese Warnung aus.

**Comment by mcm1957** [comment]
Wie löst du den Restart aus?

**Comment by jomahol** [comment]
Manuell direkt auf der Seite 'Instanzen' an der rct.0 Instanz mit dem Kreispfeil Button und den stündlichen auch direkt an der Instanz im  Expertenmodus über das UHR Symbol

**Comment by mcm1957** [comment]
looks like ack:true is missing here:

https://github.com/aruttkamp/ioBroker.rct/blob/696786a416a39eeef0a9159822a8a419c4f86a0e/main.js#L140

**Comment by aruttkamp** [comment]
Thx - corrected. comes with next version

**Comment by jomahol** [comment]
Gut, vielen Dank. :-)
